// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalR.Backplane.EFCore.Tests;

#nullable disable

namespace SignalR.Backplane.EFCore.Tests.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250913175934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("SignalR.Backplane.EFCore.Models.BackplaneAck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BackplaneMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriberId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BackplaneMessageId");

                    b.ToTable("Acks");
                });

            modelBuilder.Entity("SignalR.Backplane.EFCore.Models.BackplaneMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SignalR.Backplane.EFCore.Models.BackplaneSubscriber", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("SignalR.Backplane.EFCore.Models.BackplaneAck", b =>
                {
                    b.HasOne("SignalR.Backplane.EFCore.Models.BackplaneMessage", null)
                        .WithMany("Acks")
                        .HasForeignKey("BackplaneMessageId");
                });

            modelBuilder.Entity("SignalR.Backplane.EFCore.Models.BackplaneMessage", b =>
                {
                    b.Navigation("Acks");
                });
#pragma warning restore 612, 618
        }
    }
}
